const CountryAPI = {
  country: [    
    { key:"United States" ,name:"United States" ,value:"UNITED STATES" ,text:"United States"},
    { key:"Afghanistan" ,name:"Afghanistan" ,value:"AFGHANISTAN" ,text:"Afghanistan"},
    { key:"Albania" ,name:"Albania" ,value:"ALBANIA" ,text:"Albania"},
    { key:"Algeria" ,name:"Algeria" ,value:"ALGERIA" ,text:"Algeria"},
    { key:"American Samoa" ,name:"American Samoa" ,value:"AMERICAN SAMOA" ,text:"American Samoa"},
    { key:"Andorra" ,name:"Andorra" ,value:"ANDORRA" ,text:"Andorra"},
    { key:"Angola" ,name:"Angola" ,value:"ANGOLA" ,text:"Angola"},
    { key:"Anguilla" ,name:"Anguilla" ,value:"ANGUILLA" ,text:"Anguilla"},
    { key:"Antigua and Barbuda" ,name:"Antigua and Barbuda" ,value:"ANTIGUA AND BARBUDA" ,text:"Antigua and Barbuda"},
    { key:"Argentina" ,name:"Argentina" ,value:"ARGENTINA" ,text:"Argentina"},
    { key:"Armenia" ,name:"Armenia" ,value:"ARMENIA" ,text:"Armenia"},
    { key:"Aruba" ,name:"Aruba" ,value:"ARUBA" ,text:"Aruba"},
    { key:"Australia" ,name:"Australia" ,value:"AUSTRALIA" ,text:"Australia"},
    { key:"Austria" ,name:"Austria" ,value:"AUSTRIA" ,text:"Austria"},
    { key:"Azerbaijan" ,name:"Azerbaijan" ,value:"AZERBAIJAN" ,text:"Azerbaijan"},
    { key:"Bahamas" ,name:"Bahamas" ,value:"BAHAMAS" ,text:"Bahamas"},
    { key:"Bahrain" ,name:"Bahrain" ,value:"BAHRAIN" ,text:"Bahrain"},
    { key:"Bangladesh" ,name:"Bangladesh" ,value:"BANGLADESH" ,text:"Bangladesh"},
    { key:"Barbados" ,name:"Barbados" ,value:"BARBADOS" ,text:"Barbados"},
    { key:"Belarus" ,name:"Belarus" ,value:"BELARUS" ,text:"Belarus"},
    { key:"Belgium" ,name:"Belgium" ,value:"BELGIUM" ,text:"Belgium"},
    { key:"Belize" ,name:"Belize" ,value:"BELIZE" ,text:"Belize"},
    { key:"Benin" ,name:"Benin" ,value:"BENIN" ,text:"Benin"},
    { key:"Bermuda" ,name:"Bermuda" ,value:"BERMUDA" ,text:"Bermuda"},
    { key:"Bhutan" ,name:"Bhutan" ,value:"BHUTAN" ,text:"Bhutan"},
    { key:"Bolivia" ,name:"Bolivia" ,value:"BOLIVIA" ,text:"Bolivia"},
    { key:"Bosnia and Herzegovina" ,name:"Bosnia and Herzegovina" ,value:"BOSNIA AND HERZEGOVINA" ,text:"Bosnia and Herzegovina"},
    { key:"Botswana" ,name:"Botswana" ,value:"BOTSWANA" ,text:"Botswana"},
    { key:"Brazil" ,name:"Brazil" ,value:"BRAZIL" ,text:"Brazil"},
    { key:"British Indian Ocean Territory" ,name:"British Indian Ocean Territory" ,value:"BRITISH INDIAN OCEAN TERRITORY" ,text:"British Indian Ocean Territory"},
    { key:"Brunei Darussalam" ,name:"Brunei Darussalam" ,value:"BRUNEI DARUSSALAM" ,text:"Brunei Darussalam"},
    { key:"Bulgaria" ,name:"Bulgaria" ,value:"BULGARIA" ,text:"Bulgaria"},
    { key:"Burkina Faso" ,name:"Burkina Faso" ,value:"BURKINA FASO" ,text:"Burkina Faso"},
    { key:"Burundi" ,name:"Burundi" ,value:"BURUNDI" ,text:"Burundi"},
    { key:"Cambodia" ,name:"Cambodia" ,value:"CAMBODIA" ,text:"Cambodia"},
    { key:"Cameroon" ,name:"Cameroon" ,value:"CAMEROON" ,text:"Cameroon"},
    { key:"Canada" ,name:"Canada" ,value:"CANADA" ,text:"Canada"},
    { key:"Cape Verde" ,name:"Cape Verde" ,value:"CAPE VERDE" ,text:"Cape Verde"},
    { key:"Cayman Islands" ,name:"Cayman Islands" ,value:"CAYMAN ISLANDS" ,text:"Cayman Islands"},
    { key:"Central African Republic" ,name:"Central African Republic" ,value:"CENTRAL AFRICAN REPUBLIC" ,text:"Central African Republic"},
    { key:"Chad" ,name:"Chad" ,value:"CHAD" ,text:"Chad"},
    { key:"Chile" ,name:"Chile" ,value:"CHILE" ,text:"Chile"},
    { key:"China" ,name:"China" ,value:"CHINA" ,text:"China"},
    { key:"Christmas Island" ,name:"Christmas Island" ,value:"CHRISTMAS ISLAND" ,text:"Christmas Island"},
    { key:"Cocos (Keeling) Islands" ,name:"Cocos (Keeling) Islands" ,value:"COCOS (KEELING) ISLANDS" ,text:"Cocos (Keeling) Islands"},
    { key:"Colombia" ,name:"Colombia" ,value:"COLOMBIA" ,text:"Colombia"},
    { key:"Comoros" ,name:"Comoros" ,value:"COMOROS" ,text:"Comoros"},
    { key:"Congo" ,name:"Congo" ,value:"CONGO" ,text:"Congo"},
    { key:"Congo, the Democratic Republic of the" ,name:"Congo, the Democratic Republic of the" ,value:"CONGO, THE DEMOCRATIC REPUBLIC OF THE" ,text:"Congo, the Democratic Republic of the"},
    { key:"Cook Islands" ,name:"Cook Islands" ,value:"COOK ISLANDS" ,text:"Cook Islands"},
    { key:"Costa Rica" ,name:"Costa Rica" ,value:"COSTA RICA" ,text:"Costa Rica"},
    { key:"Cote D'Ivoire" ,name:"Cote D'Ivoire" ,value:"COTE D'IVOIRE" ,text:"Cote D'Ivoire"},
    { key:"Croatia" ,name:"Croatia" ,value:"CROATIA" ,text:"Croatia"},
    { key:"Cuba" ,name:"Cuba" ,value:"CUBA" ,text:"Cuba"},
    { key:"Cyprus" ,name:"Cyprus" ,value:"CYPRUS" ,text:"Cyprus"},
    { key:"Czech Republic" ,name:"Czech Republic" ,value:"CZECH REPUBLIC" ,text:"Czech Republic"},
    { key:"Denmark" ,name:"Denmark" ,value:"DENMARK" ,text:"Denmark"},
    { key:"Djibouti" ,name:"Djibouti" ,value:"DJIBOUTI" ,text:"Djibouti"},
    { key:"Dominica" ,name:"Dominica" ,value:"DOMINICA" ,text:"Dominica"},
    { key:"Dominican Republic" ,name:"Dominican Republic" ,value:"DOMINICAN REPUBLIC" ,text:"Dominican Republic"},
    { key:"Ecuador" ,name:"Ecuador" ,value:"ECUADOR" ,text:"Ecuador"},
    { key:"Egypt" ,name:"Egypt" ,value:"EGYPT" ,text:"Egypt"},
    { key:"El Salvador" ,name:"El Salvador" ,value:"EL SALVADOR" ,text:"El Salvador"},
    { key:"Equatorial Guinea" ,name:"Equatorial Guinea" ,value:"EQUATORIAL GUINEA" ,text:"Equatorial Guinea"},
    { key:"Eritrea" ,name:"Eritrea" ,value:"ERITREA" ,text:"Eritrea"},
    { key:"Estonia" ,name:"Estonia" ,value:"ESTONIA" ,text:"Estonia"},
    { key:"Ethiopia" ,name:"Ethiopia" ,value:"ETHIOPIA" ,text:"Ethiopia"},
    { key:"Falkland Islands (Malvinas)" ,name:"Falkland Islands (Malvinas)" ,value:"FALKLAND ISLANDS (MALVINAS)" ,text:"Falkland Islands (Malvinas)"},
    { key:"Faroe Islands" ,name:"Faroe Islands" ,value:"FAROE ISLANDS" ,text:"Faroe Islands"},
    { key:"Fiji" ,name:"Fiji" ,value:"FIJI" ,text:"Fiji"},
    { key:"Finland" ,name:"Finland" ,value:"FINLAND" ,text:"Finland"},
    { key:"France" ,name:"France" ,value:"FRANCE" ,text:"France"},
    { key:"French Guiana" ,name:"French Guiana" ,value:"FRENCH GUIANA" ,text:"French Guiana"},
    { key:"French Polynesia" ,name:"French Polynesia" ,value:"FRENCH POLYNESIA" ,text:"French Polynesia"},
    { key:"French Southern Territories" ,name:"French Southern Territories" ,value:"FRENCH SOUTHERN TERRITORIES" ,text:"French Southern Territories"},
    { key:"Gabon" ,name:"Gabon" ,value:"GABON" ,text:"Gabon"},
    { key:"Gambia" ,name:"Gambia" ,value:"GAMBIA" ,text:"Gambia"},
    { key:"Georgia" ,name:"Georgia" ,value:"GEORGIA" ,text:"Georgia"},
    { key:"Germany" ,name:"Germany" ,value:"GERMANY" ,text:"Germany"},
    { key:"Ghana" ,name:"Ghana" ,value:"GHANA" ,text:"Ghana"},
    { key:"Gibraltar" ,name:"Gibraltar" ,value:"GIBRALTAR" ,text:"Gibraltar"},
    { key:"Greece" ,name:"Greece" ,value:"GREECE" ,text:"Greece"},
    { key:"Greenland" ,name:"Greenland" ,value:"GREENLAND" ,text:"Greenland"},
    { key:"Grenada" ,name:"Grenada" ,value:"GRENADA" ,text:"Grenada"},
    { key:"Guadeloupe" ,name:"Guadeloupe" ,value:"GUADELOUPE" ,text:"Guadeloupe"},
    { key:"Guam" ,name:"Guam" ,value:"GUAM" ,text:"Guam"},
    { key:"Guatemala" ,name:"Guatemala" ,value:"GUATEMALA" ,text:"Guatemala"},
    { key:"Guinea" ,name:"Guinea" ,value:"GUINEA" ,text:"Guinea"},
    { key:"Guinea-Bissau" ,name:"Guinea-Bissau" ,value:"GUINEA-BISSAU" ,text:"Guinea-Bissau"},
    { key:"Guyana" ,name:"Guyana" ,value:"GUYANA" ,text:"Guyana"},
    { key:"Haiti" ,name:"Haiti" ,value:"HAITI" ,text:"Haiti"},
    { key:"Holy See (Vatican City State)" ,name:"Holy See (Vatican City State)" ,value:"HOLY SEE (VATICAN CITY STATE)" ,text:"Holy See (Vatican City State)"},
    { key:"Honduras" ,name:"Honduras" ,value:"HONDURAS" ,text:"Honduras"},
    { key:"Hong Kong" ,name:"Hong Kong" ,value:"HONG KONG" ,text:"Hong Kong"},
    { key:"Hungary" ,name:"Hungary" ,value:"HUNGARY" ,text:"Hungary"},
    { key:"Iceland" ,name:"Iceland" ,value:"ICELAND" ,text:"Iceland"},
    { key:"India" ,name:"India" ,value:"INDIA" ,text:"India"},
    { key:"Indonesia" ,name:"Indonesia" ,value:"INDONESIA" ,text:"Indonesia"},
    { key:"Iran, Islamic Republic of" ,name:"Iran, Islamic Republic of" ,value:"IRAN, ISLAMIC REPUBLIC OF" ,text:"Iran, Islamic Republic of"},
    { key:"Iraq" ,name:"Iraq" ,value:"IRAQ" ,text:"Iraq"},
    { key:"Ireland" ,name:"Ireland" ,value:"IRELAND" ,text:"Ireland"},
    { key:"Israel" ,name:"Israel" ,value:"ISRAEL" ,text:"Israel"},
    { key:"Italy" ,name:"Italy" ,value:"ITALY" ,text:"Italy"},
    { key:"Jamaica" ,name:"Jamaica" ,value:"JAMAICA" ,text:"Jamaica"},
    { key:"Japan" ,name:"Japan" ,value:"JAPAN" ,text:"Japan"},
    { key:"Jordan" ,name:"Jordan" ,value:"JORDAN" ,text:"Jordan"},
    { key:"Kazakhstan" ,name:"Kazakhstan" ,value:"KAZAKHSTAN" ,text:"Kazakhstan"},
    { key:"Kenya" ,name:"Kenya" ,value:"KENYA" ,text:"Kenya"},
    { key:"Kiribati" ,name:"Kiribati" ,value:"KIRIBATI" ,text:"Kiribati"},
    { key:"Kuwait" ,name:"Kuwait" ,value:"KUWAIT" ,text:"Kuwait"},
    { key:"Kyrgyzstan" ,name:"Kyrgyzstan" ,value:"KYRGYZSTAN" ,text:"Kyrgyzstan"},
    { key:"Lao People's Democratic Republic" ,name:"Lao People's Democratic Republic" ,value:"LAO PEOPLE'S DEMOCRATIC REPUBLIC" ,text:"Lao People's Democratic Republic"},
    { key:"Latvia" ,name:"Latvia" ,value:"LATVIA" ,text:"Latvia"},
    { key:"Lebanon" ,name:"Lebanon" ,value:"LEBANON" ,text:"Lebanon"},
    { key:"Lesotho" ,name:"Lesotho" ,value:"LESOTHO" ,text:"Lesotho"},
    { key:"Liberia" ,name:"Liberia" ,value:"LIBERIA" ,text:"Liberia"},
    { key:"Libyan Arab Jamahiriya" ,name:"Libyan Arab Jamahiriya" ,value:"LIBYAN ARAB JAMAHIRIYA" ,text:"Libyan Arab Jamahiriya"},
    { key:"Liechtenstein" ,name:"Liechtenstein" ,value:"LIECHTENSTEIN" ,text:"Liechtenstein"},
    { key:"Lithuania" ,name:"Lithuania" ,value:"LITHUANIA" ,text:"Lithuania"},
    { key:"Luxembourg" ,name:"Luxembourg" ,value:"LUXEMBOURG" ,text:"Luxembourg"},
    { key:"Macao" ,name:"Macao" ,value:"MACAO" ,text:"Macao"},
    { key:"Macedonia" ,name:"Macedonia" ,value:"MACEDONIA" ,text:"Macedonia"},
    { key:"Madagascar" ,name:"Madagascar" ,value:"MADAGASCAR" ,text:"Madagascar"},
    { key:"Malawi" ,name:"Malawi" ,value:"MALAWI" ,text:"Malawi"},
    { key:"Malaysia" ,name:"Malaysia" ,value:"MALAYSIA" ,text:"Malaysia"},
    { key:"Maldives" ,name:"Maldives" ,value:"MALDIVES" ,text:"Maldives"},
    { key:"Mali" ,name:"Mali" ,value:"MALI" ,text:"Mali"},
    { key:"Malta" ,name:"Malta" ,value:"MALTA" ,text:"Malta"},
    { key:"Marshall Islands" ,name:"Marshall Islands" ,value:"MARSHALL ISLANDS" ,text:"Marshall Islands"},
    { key:"Martinique" ,name:"Martinique" ,value:"MARTINIQUE" ,text:"Martinique"},
    { key:"Mauritania" ,name:"Mauritania" ,value:"MAURITANIA" ,text:"Mauritania"},
    { key:"Mauritius" ,name:"Mauritius" ,value:"MAURITIUS" ,text:"Mauritius"},
    { key:"Mayotte" ,name:"Mayotte" ,value:"MAYOTTE" ,text:"Mayotte"},
    { key:"Mexico" ,name:"Mexico" ,value:"MEXICO" ,text:"Mexico"},
    { key:"Micronesia, Federated States of" ,name:"Micronesia, Federated States of" ,value:"MICRONESIA, FEDERATED STATES OF" ,text:"Micronesia, Federated States of"},
    { key:"Moldova, Republic of" ,name:"Moldova, Republic of" ,value:"MOLDOVA, REPUBLIC OF" ,text:"Moldova, Republic of"},
    { key:"Monaco" ,name:"Monaco" ,value:"MONACO" ,text:"Monaco"},
    { key:"Mongolia" ,name:"Mongolia" ,value:"MONGOLIA" ,text:"Mongolia"},
    { key:"Montenegro" ,name:"Montenegro" ,value:"MONTENEGRO" ,text:"Montenegro"},
    { key:"Montserrat" ,name:"Montserrat" ,value:"MONTSERRAT" ,text:"Montserrat"},
    { key:"Morocco" ,name:"Morocco" ,value:"MOROCCO" ,text:"Morocco"},
    { key:"Mozambique" ,name:"Mozambique" ,value:"MOZAMBIQUE" ,text:"Mozambique"},
    { key:"Myanmar" ,name:"Myanmar" ,value:"MYANMAR" ,text:"Myanmar"},
    { key:"Namibia" ,name:"Namibia" ,value:"NAMIBIA" ,text:"Namibia"},
    { key:"Nauru" ,name:"Nauru" ,value:"NAURU" ,text:"Nauru"},
    { key:"Nepal" ,name:"Nepal" ,value:"NEPAL" ,text:"Nepal"},
    { key:"Netherlands" ,name:"Netherlands" ,value:"NETHERLANDS" ,text:"Netherlands"},
    { key:"Netherlands Antilles" ,name:"Netherlands Antilles" ,value:"NETHERLANDS ANTILLES" ,text:"Netherlands Antilles"},
    { key:"New Caledonia" ,name:"New Caledonia" ,value:"NEW CALEDONIA" ,text:"New Caledonia"},
    { key:"New Zealand" ,name:"New Zealand" ,value:"NEW ZEALAND" ,text:"New Zealand"},
    { key:"Nicaragua" ,name:"Nicaragua" ,value:"NICARAGUA" ,text:"Nicaragua"},
    { key:"Niger" ,name:"Niger" ,value:"NIGER" ,text:"Niger"},
    { key:"Nigeria" ,name:"Nigeria" ,value:"NIGERIA" ,text:"Nigeria"},
    { key:"Niue" ,name:"Niue" ,value:"NIUE" ,text:"Niue"},
    { key:"Norfolk Island" ,name:"Norfolk Island" ,value:"NORFOLK ISLAND" ,text:"Norfolk Island"},
    { key:"North Korea" ,name:"North Korea" ,value:"NORTH KOREA" ,text:"North Korea"},
    { key:"Northern Mariana Islands" ,name:"Northern Mariana Islands" ,value:"NORTHERN MARIANA ISLANDS" ,text:"Northern Mariana Islands"},
    { key:"Norway" ,name:"Norway" ,value:"NORWAY" ,text:"Norway"},
    { key:"Oman" ,name:"Oman" ,value:"OMAN" ,text:"Oman"},
    { key:"Pakistan" ,name:"Pakistan" ,value:"PAKISTAN" ,text:"Pakistan"},
    { key:"Palau" ,name:"Palau" ,value:"PALAU" ,text:"Palau"},
    { key:"Panama" ,name:"Panama" ,value:"PANAMA" ,text:"Panama"},
    { key:"Papua New Guinea" ,name:"Papua New Guinea" ,value:"PAPUA NEW GUINEA" ,text:"Papua New Guinea"},
    { key:"Paraguay" ,name:"Paraguay" ,value:"PARAGUAY" ,text:"Paraguay"},
    { key:"Peru" ,name:"Peru" ,value:"PERU" ,text:"Peru"},
    { key:"Philippines" ,name:"Philippines" ,value:"PHILIPPINES" ,text:"Philippines"},
    { key:"Pitcairn" ,name:"Pitcairn" ,value:"PITCAIRN" ,text:"Pitcairn"},
    { key:"Poland" ,name:"Poland" ,value:"POLAND" ,text:"Poland"},
    { key:"Portugal" ,name:"Portugal" ,value:"PORTUGAL" ,text:"Portugal"},
    { key:"Puerto Rico" ,name:"Puerto Rico" ,value:"PUERTO RICO" ,text:"Puerto Rico"},
    { key:"Qatar" ,name:"Qatar" ,value:"QATAR" ,text:"Qatar"},
    { key:"Reunion" ,name:"Reunion" ,value:"REUNION" ,text:"Reunion"},
    { key:"Romania" ,name:"Romania" ,value:"ROMANIA" ,text:"Romania"},
    { key:"Russian Federation" ,name:"Russian Federation" ,value:"RUSSIAN FEDERATION" ,text:"Russian Federation"},
    { key:"Rwanda" ,name:"Rwanda" ,value:"RWANDA" ,text:"Rwanda"},
    { key:"Saint Helena" ,name:"Saint Helena" ,value:"SAINT HELENA" ,text:"Saint Helena"},
    { key:"Saint Kitts and Nevis" ,name:"Saint Kitts and Nevis" ,value:"SAINT KITTS AND NEVIS" ,text:"Saint Kitts and Nevis"},
    { key:"Saint Lucia" ,name:"Saint Lucia" ,value:"SAINT LUCIA" ,text:"Saint Lucia"},
    { key:"Saint Pierre and Miquelon" ,name:"Saint Pierre and Miquelon" ,value:"SAINT PIERRE AND MIQUELON" ,text:"Saint Pierre and Miquelon"},
    { key:"Saint Vincent and the Grenadines" ,name:"Saint Vincent and the Grenadines" ,value:"SAINT VINCENT AND THE GRENADINES" ,text:"Saint Vincent and the Grenadines"},
    { key:"Samoa" ,name:"Samoa" ,value:"SAMOA" ,text:"Samoa"},
    { key:"San Marino" ,name:"San Marino" ,value:"SAN MARINO" ,text:"San Marino"},
    { key:"Sao Tome and Principe" ,name:"Sao Tome and Principe" ,value:"SAO TOME AND PRINCIPE" ,text:"Sao Tome and Principe"},
    { key:"Saudi Arabia" ,name:"Saudi Arabia" ,value:"SAUDI ARABIA" ,text:"Saudi Arabia"},
    { key:"Senegal" ,name:"Senegal" ,value:"SENEGAL" ,text:"Senegal"},
    { key:"Serbia" ,name:"Serbia" ,value:"SERBIA" ,text:"Serbia"},
    { key:"Seychelles" ,name:"Seychelles" ,value:"SEYCHELLES" ,text:"Seychelles"},
    { key:"Sierra Leone" ,name:"Sierra Leone" ,value:"SIERRA LEONE" ,text:"Sierra Leone"},
    { key:"Singapore" ,name:"Singapore" ,value:"SINGAPORE" ,text:"Singapore"},
    { key:"Slovakia" ,name:"Slovakia" ,value:"SLOVAKIA" ,text:"Slovakia"},
    { key:"Slovenia" ,name:"Slovenia" ,value:"SLOVENIA" ,text:"Slovenia"},
    { key:"Solomon Islands" ,name:"Solomon Islands" ,value:"SOLOMON ISLANDS" ,text:"Solomon Islands"},
    { key:"Somalia" ,name:"Somalia" ,value:"SOMALIA" ,text:"Somalia"},
    { key:"South Africa" ,name:"South Africa" ,value:"SOUTH AFRICA" ,text:"South Africa"},
    { key:"South Korea" ,name:"South Korea" ,value:"SOUTH KOREA" ,text:"South Korea"},
    { key:"Spain" ,name:"Spain" ,value:"SPAIN" ,text:"Spain"},
    { key:"Sri Lanka" ,name:"Sri Lanka" ,value:"SRI LANKA" ,text:"Sri Lanka"},
    { key:"Sudan" ,name:"Sudan" ,value:"SUDAN" ,text:"Sudan"},
    { key:"Suri,name" ,name:"Suri,name" ,value:"SURINAME" ,text:"Suri,name"},
    { key:"Swaziland" ,name:"Swaziland" ,value:"SWAZILAND" ,text:"Swaziland"},
    { key:"Sweden" ,name:"Sweden" ,value:"SWEDEN" ,text:"Sweden"},
    { key:"Switzerland" ,name:"Switzerland" ,value:"SWITZERLAND" ,text:"Switzerland"},
    { key:"Syrian Arab Republic" ,name:"Syrian Arab Republic" ,value:"SYRIAN ARAB REPUBLIC" ,text:"Syrian Arab Republic"},
    { key:"Taiwan, Province of China" ,name:"Taiwan, Province of China" ,value:"TAIWAN, PROVINCE OF CHINA" ,text:"Taiwan, Province of China"},
    { key:"Tajikistan" ,name:"Tajikistan" ,value:"TAJIKISTAN" ,text:"Tajikistan"},
    { key:"Tanzania, United Republic of" ,name:"Tanzania, United Republic of" ,value:"TANZANIA, UNITED REPUBLIC OF" ,text:"Tanzania, United Republic of"},
    { key:"Thailand" ,name:"Thailand" ,value:"THAILAND" ,text:"Thailand"},
    { key:"Togo" ,name:"Togo" ,value:"TOGO" ,text:"Togo"},
    { key:"Tokelau" ,name:"Tokelau" ,value:"TOKELAU" ,text:"Tokelau"},
    { key:"Tonga" ,name:"Tonga" ,value:"TONGA" ,text:"Tonga"},
    { key:"Trinidad and Tobago" ,name:"Trinidad and Tobago" ,value:"TRINIDAD AND TOBAGO" ,text:"Trinidad and Tobago"},
    { key:"Tunisia" ,name:"Tunisia" ,value:"TUNISIA" ,text:"Tunisia"},
    { key:"Turkey" ,name:"Turkey" ,value:"TURKEY" ,text:"Turkey"},
    { key:"Turkmenistan" ,name:"Turkmenistan" ,value:"TURKMENISTAN" ,text:"Turkmenistan"},
    { key:"Turks and Caicos Islands" ,name:"Turks and Caicos Islands" ,value:"TURKS AND CAICOS ISLANDS" ,text:"Turks and Caicos Islands"},
    { key:"Tuvalu" ,name:"Tuvalu" ,value:"TUVALU" ,text:"Tuvalu"},
    { key:"Uganda" ,name:"Uganda" ,value:"UGANDA" ,text:"Uganda"},
    { key:"Ukraine" ,name:"Ukraine" ,value:"UKRAINE" ,text:"Ukraine"},
    { key:"United Arab Emirates" ,name:"United Arab Emirates" ,value:"UNITED ARAB EMIRATES" ,text:"United Arab Emirates"},
    { key:"United Kingdom" ,name:"United Kingdom" ,value:"UNITED KINGDOM" ,text:"United Kingdom"},
    { key:"Uruguay" ,name:"Uruguay" ,value:"URUGUAY" ,text:"Uruguay"},
    { key:"Uzbekistan" ,name:"Uzbekistan" ,value:"UZBEKISTAN" ,text:"Uzbekistan"},
    { key:"Vanuatu" ,name:"Vanuatu" ,value:"VANUATU" ,text:"Vanuatu"},
    { key:"Venezuela" ,name:"Venezuela" ,value:"VENEZUELA" ,text:"Venezuela"},
    { key:"Viet Nam" ,name:"Viet Nam" ,value:"VIET NAM" ,text:"Viet Nam"},
    { key:"Virgin Islands, British" ,name:"Virgin Islands, British" ,value:"VIRGIN ISLANDS, BRITISH" ,text:"Virgin Islands, British"},
    { key:"Virgin Islands, U.s." ,name:"Virgin Islands, U.s." ,value:"VIRGIN ISLANDS, U.S." ,text:"Virgin Islands, U.s."},
    { key:"Wallis and Futuna" ,name:"Wallis and Futuna" ,value:"WALLIS AND FUTUNA" ,text:"Wallis and Futuna"},
    { key:"Western Sahara" ,name:"Western Sahara" ,value:"WESTERN SAHARA" ,text:"Western Sahara"},
    { key:"Yemen" ,name:"Yemen" ,value:"YEMEN" ,text:"Yemen"},
    { key:"Zambia" ,name:"Zambia" ,value:"ZAMBIA" ,text:"Zambia"},
    { key:"Zimbabwe" ,name:"Zimbabwe" ,value:"ZIMBABWE" ,text:"Zimbabwe"}
  ],
  all: function() { return this.country},
}

export default CountryAPI
