const LocationAPI = {
  location: [    
    { key:'Bangalore Marketing Campaigns',name:"Bangalore Marketing Campaigns", text:'Bangalore Marketing Campaigns', value:'Bangalore Marketing Campaigns'},
    { key:'Athens Marketing Campaigns',name:"Athens Marketing Campaigns", text:'Athens Marketing Campaigns', value:'Athens Marketing Campaigns'},
    { key:'BHARAT JAI',name:"BHARAT JAIN", text:'BHARAT JAI', value:'BHARAT JAI'},
    { key:'Collection Bali',name:"Collection Bali", text:'Collection Bali', value:'Collection Bali'},
    { key:'CHECKIN',name:"CHECKIN", text:'CHECKIN', value:'CHECKIN'},
    { key:'Event Chairman Invite',name:"Event Chairman Invite", text:'Event Chairman Invite', value:'Event Chairman Invite'},
    { key:'Event Rugby',name:"Event Rugby", text:'Event Rugby', value:'Event Rugby'},
    { key:'Facebook Campaign',name:"Facebook Campaign", text:'Facebook Campaign', value:'Facebook Campaign'},
    { key:'HAPPY',name:"HAPPY", text:'HAPPY', value:'HAPPY'},
    { key:'Inbound Call',name:"Inbound Call", text:'Inbound Call', value:'Inbound Call'},
    { key:'Karma Bavaria',name:"Karma Bavaria", text:'Karma Bavaria', value:'Karma Bavaria'},
    { key:'Karma BeachClub',name:"Karma BeachClub", text:'Karma BeachClub', value:'Karma BeachClub'},
    { key:'Karma Chakra',name:"Karma Chakra", text:'Karma Chakra', value:'Karma Chakra'},
    { key:'Karma Haveli',name:"Karma Haveli", text:'Karma Haveli', value:'Karma Haveli'},
    { key:'Karma Grove',name:"Karma Grove", text:'Karma Grove', value:'Karma Grove'},
    { key:'Karma Jimbaran',name:"Karma Jimbaran", text:'Karma Jimbaran', value:'Karma Jimbaran'},
    { key:'Karma Kandara',name:"Karma Kandara", text:'Karma Kandara', value:'Karma Kandara'},
    { key:'Karma Mayura',name:"Karma Mayura", text:'Karma Mayura', value:'Karma Mayura'},
    { key:'Karma Reef',name:"Karma Reef", text:'Karma Reef', value:'Karma Reef'},
    { key:'Karma Rottnest',name:"Karma Rottnest", text:'Karma Rottnest', value:'Karma Rottnest'},
    { key:'Karma Royal Benaulim Goa',name:"Karma Royal Benaulim Goa", text:'Karma Royal Benaulim Goa', value:'Karma Royal Benaulim Goa'},
    { key:'Karma Royal Chiang Mai Thailand',name:"Karma Royal Chiang Mai Thailand", text:'Karma Royal Chiang Mai Thailand', value:'Karma Royal Chiang Mai Thailand'},
    { key:'Karma Royal Candidasa Bali',name:"Karma Royal Candidasa Bali", text:'Karma Royal Candidasa Bali', value:'Karma Royal Candidasa Bali'},
    { key:'Karma Royal Phuket Thailand',name:"Karma Royal Phuket Thailand", text:'Karma Royal Phuket Thailand', value:'Karma Royal Phuket Thailand'},
    { key:'Karma Royal Haathi Mahal Goa',name:"Karma Royal Haathi Mahal Goa", text:'Karma Royal Haathi Mahal Goa', value:'Karma Royal Haathi Mahal Goa'},
    { key:'Karma Royal Jimbaran Bali',name:"Karma Royal Jimbaran Bali", text:'Karma Royal Jimbaran Bali', value:'Karma Royal Jimbaran Bali'},
    { key:'Karma Royal MonteRio Goa',name:"Karma Royal MonteRio Goa", text:'Karma Royal MonteRio Goa', value:'Karma Royal MonteRio Goa'},
    { key:'Karma Royal Palms Goa',name:"Karma Royal Palms Goa", text:'Karma Royal Palms Goa', value:'Karma Royal Palms Goa'},
    { key:'Karma Royal Sanur Bal',name:"Karma Royal Sanur Bali", text:'Karma Royal Sanur Bal', value:'Karma Royal Sanur Bal'},
    { key:'Karma Royal Villea Crete',name:"Karma Royal Villea Crete", text:'Karma Royal Villea Crete', value:'Karma Royal Villea Crete'},
    { key:'Karma St Martin',name:"Karma St Martins", text:'Karma St Martin', value:'Karma St Martin'},
    { key:'MEGA',name:"MEGA", text:'MEGA', value:'MEGA'},
    { key:'MAGIC-FC',name:"MAGIC-FC", text:'MAGIC-FC', value:'MAGIC-FC'},
    { key:'NETBALLWA',name:"NETBALLWA", text:'NETBALLWA', value:'NETBALLWA'},
    { key:'Owner',name:"Owner", text:'Owner', value:'Owner'},
    { key:'PINKTANK ',name:"PINKTANK", text:'PINKTANK ', value:'PINKTANK '},
    { key:'RUGBY ',name:"RUGBY", text:'RUGBY ', value:'RUGBY '},
    { key:'Sales Deck Bavaria',name:"Sales Deck Bavaria", text:'Sales Deck Bavaria', value:'Sales Deck Bavaria'},
    { key:'Sales Deck Bali',name:"Sales Deck Bali", text:'Sales Deck Bali', value:'Sales Deck Bali'},
    { key:'Sales Deck Cold Line Reception Haathi Mahal',name:"Sales Deck Cold Line Reception Haathi Mahal", text:'Sales Deck Cold Line Reception Haathi Mahal', value:'Sales Deck Cold Line Reception Haathi Mahal'},
    { key:'Sales Deck Cold Line Reception MonteRi',name:"Sales Deck Cold Line Reception MonteRio", text:'Sales Deck Cold Line Reception MonteRi', value:'Sales Deck Cold Line Reception MonteRi'},
    { key:'SWIM16 ',name:"SWIM16", text:'SWIM16 ', value:'SWIM16 '},
    { key:'SWIM17',name:"SWIM17", text:'SWIM17', value:'SWIM17'},
    { key:'STOKES and MONTCREIFF',name:"STOKES and MONTCREIFF", text:'STOKES and MONTCREIFF', value:'STOKES and MONTCREIFF'},
    { key:'THE BALI BIBLE ',name:"THE BALI BIBLE", text:'THE BALI BIBLE ', value:'THE BALI BIBLE '},
    { key:'VIP',name:"VIP", text:'VIP', value:'VIP'},
    { key:'Website form',name:"Website form", text:'Website form', value:'Website form'},
    { key:'Other',name:"Other", text:'Other', value:'Other'}
  ],
  all: function() { return this.location},
}

export default LocationAPI
